name: Ruff Linter

on:
  workflow_dispatch:
  push:

jobs:
  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # for non PR runs we just checkout the default, which is a sha on a branch probably
        uses: actions/checkout@v4
      
      - name: Install Ruff
        run: pip install ruff

        # run: pip install -r .github/requirements.txt --break-system-packages

      - name: Run Ruff Linter
        run: ruff check --config .github/ruff.toml .